routes/admin.php
<?php

Route::get('/', 'AdminController@index')->name('home');
Route::get('reports', 'ReportsController@index')->name('reports');

//User and Authentications related
Route::resource('roles', 'RolesController');
Route::resource('users', 'UsersController');

//Visit related
Route::resource('visits', 'VisitsController');
Route::resource('visit-types', 'VisitTypesController');
Route::resource('activities', 'ActivitiesController');
Route::resource('larvae', 'LarvaeController');
Route::resource('building-statuses', 'BuildingStatusesController');
Route::resource('containers', 'ContainersController');
Route::resource('treatments', 'TreatmentsController');

//Notification related
Route::get('notifications/status', 'ReportsController@notificationsByStatus');
Route::get('notifications/age', 'ReportsController@notificationsByAge');
Route::get('notifications/regions', 'ReportsController@notificationsByRegion');
Route::resource('notifications', 'NotificationsController');
Route::resource('examinations', 'ExaminationsController');

//Location related
//State
Route::get('states/{id}/cities', 'StatesController@cities');
Route::get('states/search', 'StatesController@search');
Route::resource('states', 'StatesController');
//City
Route::get('cities/{id}/regions', 'CitiesController@regions');
Route::get('cities/search', 'CitiesController@search');
Route::resource('cities', 'CitiesController');
//Region
Route::get('regions/{id}/districts', 'RegionsController@districts');
Route::get('regions/search', 'RegionsController@search');
Route::resource('regions', 'RegionsController');
//District
Route::get('districts/{id}/streets', 'DistrictsController@streets');
Route::get('districts/search', 'DistrictsController@search');
Route::resource('districts', 'DistrictsController');
//Streets
Route::get('streets/{id}/buildings', 'StreetsController@getBuildings');
Route::get('streets/search', 'StreetsController@search');
Route::resource('streets', 'StreetsController');
//Buildings
Route::get('buildings/search', 'BuildingsController@search');
Route::resource('buildings', 'BuildingsController');
Route::resource('building-types', 'BuildingTypesController');

//Settings
Route::get('settings', 'SettingsController@index');
Route::post('settings', 'SettingsController@store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
$router->get('/', 'PublicController@index');
$router->get('vigilancia', 'PublicController@vigilancia');
$router->get('dengue', 'PublicController@dengue');
$router->get('contato', [ 'as' => 'contato', 'uses' => 'PublicController@getContato' ]);
$router->post('contato', 'PublicController@postContato');
$router->get('notifications/points', 'NotificationsController@positives');
$router->get('visits/points', 'VisitsController@getPoints');
$router->get('geocoding/{address}', 'ApiController@getGeocoding');

$router->auth();

app/Http/Controllers/BuildingTypesController.php
<?php

namespace AlphaDengue\Http\Controllers;

use AlphaDengue\BuildingType;
use AlphaDengue\Http\Requests;
use AlphaDengue\Http\Controllers\Controller;

use AlphaDengue\Http\Requests\BuildingTypeRequest;
use Illuminate\Http\Request;

class BuildingTypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $building_types = BuildingType::all();

        return view('building-types.index', compact('building_types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $building_type = new BuildingType;

        return view('building-types.create', compact('building_type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BuildingTypeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BuildingTypeRequest $request)
    {
        BuildingType::create($request->all());

        $request->session()->flash('message_type', 'success');
        $request->session()->flash('message', 'Tipo de Imóvel criado com sucesso!');

        return redirect('admin/building-types');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(BuildingType $building_type)
    {
        return response()->json(
            $building_type
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $building_type = BuildingType::findOrFail($id);

        return view('building-types.edit', compact('building_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @param BuildingTypeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update($id, BuildingTypeRequest $request)
    {
        $building_type = BuildingType::findOrFail($id);
        $building_type->update($request->all());

        \Session::flash('message_type', 'success');
        \Session::flash('message', 'Tipo de imóvel atualizado com sucesso!');

        return redirect('/admin/building-types');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        $delete_count = BuildingType::destroy($id);

        if ($delete_count != 1) {
            \Session::flash('message_type', 'danger');
            \Session::flash('message', 'Erro ao excluir tipo de imóvel!');
        } else {
            \Session::flash('message_type', 'success');
            \Session::flash('message', 'Tipo de imóvel excluido com sucesso!');
        }

        return redirect('/admin/building-types');
    }
}

resources/views/building-types/_form.blade.php
{{ csrf_field() }}
<label for="name">Descrição:</label>
<input type="text" name="name" id="name" value="{{ old('name', $building_type->name) }}">
<button type="submit" class="btn btn-primary">Salvar</button>

resources/views/building-types/create.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Novo Tipo de Imóvel</h2>
    <a href="/admin/building-types">Ver todos</a>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('building-types.store') }}">
            @include('building-types._form')
        </form>
    </div>
@stop

resources/views/building-types/edit.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Editar Tipo de Imóvel</h2>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('building-types.update', [ $building_type->id ]) }}">
            {{ method_field('PUT') }}
            @include('building-types._form')
        </form>
    </div>
@stop

resources/views/building-types/index.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Tipos de Imóveis</h2>
    <a href="/admin/building-types/create">Adicionar novo</a>
    @include('errors.list')
    @include('partials._messages')
    <div class="dash-content">
        <table>
            <thead>
            <tr>
                <th>#</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($building_types as $type)
                <tr>
                    <td>{{ $type->id }}</td>
                    <td>{{ $type->name }}</td>
                    <td>
                        <a href="{{ action('BuildingTypesController@show', $type->id) }}" class="btn btn-primary btn-xs">
                            Ver
                        </a>
                        <a href="{{ action('BuildingTypesController@edit', $type->id) }}" class="btn btn-info btn-xs">
                            Editar
                        </a>
                        <form method="POST"
                              class="form--inline"
                              action="{{ action('BuildingTypesController@destroy', [ $type->id ]) }}"
                            >
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger btn-xs">
                                Excluir
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop