routes/admin.php
<?php

Route::get('/', 'AdminController@index')->name('home');
Route::get('reports', 'ReportsController@index')->name('reports');

//User and Authentications related
Route::resource('roles', 'RolesController');
Route::resource('users', 'UsersController');

//Visit related
Route::resource('visits', 'VisitsController');
Route::resource('visit-types', 'VisitTypesController');
Route::resource('activities', 'ActivitiesController');
Route::resource('larvae', 'LarvaeController');
Route::resource('building-statuses', 'BuildingStatusesController');
Route::resource('containers', 'ContainersController');
Route::resource('treatments', 'TreatmentsController');

//Notification related
Route::get('notifications/status', 'ReportsController@notificationsByStatus');
Route::get('notifications/age', 'ReportsController@notificationsByAge');
Route::get('notifications/regions', 'ReportsController@notificationsByRegion');
Route::resource('notifications', 'NotificationsController');
Route::resource('examinations', 'ExaminationsController');

//Location related
//State
Route::get('states/{id}/cities', 'StatesController@cities');
Route::get('states/search', 'StatesController@search');
Route::resource('states', 'StatesController');
//City
Route::get('cities/{id}/regions', 'CitiesController@regions');
Route::get('cities/search', 'CitiesController@search');
Route::resource('cities', 'CitiesController');
//Region
Route::get('regions/{id}/districts', 'RegionsController@districts');
Route::get('regions/search', 'RegionsController@search');
Route::resource('regions', 'RegionsController');
//District
Route::get('districts/{id}/streets', 'DistrictsController@streets');
Route::get('districts/search', 'DistrictsController@search');
Route::resource('districts', 'DistrictsController');
//Streets
Route::get('streets/{id}/buildings', 'StreetsController@getBuildings');
Route::get('streets/search', 'StreetsController@search');
Route::resource('streets', 'StreetsController');
//Buildings
Route::get('buildings/search', 'BuildingsController@search');
Route::resource('buildings', 'BuildingsController');
Route::resource('building-types', 'BuildingTypesController');

//Settings
Route::get('settings', 'SettingsController@index');
Route::post('settings', 'SettingsController@store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
$router->get('/', 'PublicController@index');
$router->get('vigilancia', 'PublicController@vigilancia');
$router->get('dengue', 'PublicController@dengue');
$router->get('contato', [ 'as' => 'contato', 'uses' => 'PublicController@getContato' ]);
$router->post('contato', 'PublicController@postContato');
$router->get('notifications/points', 'NotificationsController@positives');
$router->get('visits/points', 'VisitsController@getPoints');
$router->get('geocoding/{address}', 'ApiController@getGeocoding');

$router->auth();

app/Region.php
<?php

namespace AlphaDengue;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'city_id'
    ];

    /**
     * Retrieves the districts of this region
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function districts()
    {
        return $this->hasMany(District::class)->orderBy('name');
    }

    /**
     * Returns the city of this region
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function city()
    {
        return $this->belongsTo(City::class);
    }

    /**
     * Returns the state for this region based on its city.
     *
     * @return State
     */
    public function state()
    {
        return $this->city->state;
    }
}

app/Http/Controllers/RegionsController.php
<?php

namespace AlphaDengue\Http\Controllers;

use AlphaDengue\City;
use AlphaDengue\State;
use AlphaDengue\Region;
use Illuminate\Http\Request;
use AlphaDengue\Http\Requests\RegionRequest;

class RegionsController extends Controller
{
    private $region;

    /**
     * RegionsController constructor.
     * @param Region $region
     */
    public function __construct(Region $region)
    {
        $this->region = $region;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $regionsQuery = $this->region->orderBy('name');

        if ($request->has('q')) {
            $query = $request->query('q');
            $regionsQuery = $regionsQuery->where('name', 'ilike', '%' . $query . '%');
        }

        $regions = $regionsQuery->with('city.state')->paginate();

        return view('regions.index', compact('regions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $region = new Region;
        $states = State::orderBy('name')->pluck('name', 'id');
        $cities = [];

        return view('regions.create', compact('region', 'states', 'cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RegionRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(RegionRequest $request)
    {
        Region::create($request->all());

        $request->session()->flash('message_type', 'success');
        $request->session()->flash('message', 'Região cadastrada com sucesso!');

        return redirect('/admin/regions');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $region = Region::findOrFail($id);

        return view('regions.show', compact('region'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $region = Region::findOrFail($id);
        $states = State::orderBy('name')->pluck('name', 'id')->all();
        $cities = City::where('state_id', '=', $region->city->state_id)->pluck('name', 'id');

        return view('regions.edit', compact('region', 'cities', 'states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @param RegionRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update($id, RegionRequest $request)
    {
        $region = Region::findOrFail($id);
        $region->update($request->all());

        \Session::flash('message_type', 'success');
        \Session::flash('message', 'Região atualizada com sucesso!');

        return redirect('/admin/regions');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete_count = Region::destroy($id);

        if ($delete_count != 1) {
            \Session::flash('message_type', 'danger');
            \Session::flash('message', 'Erro ao excluir região!');
        } else {
            \Session::flash('message_type', 'success');
            \Session::flash('message', 'Região excluida com sucesso!');
        }

        return redirect('/admin/regions');
    }

    /**
     * Get the districts of the region
     *
     * @param $id
     * @return mixed
     */
    public function districts($id)
    {
        $region = Region::findOrFail($id);

        return response()->json([
            'data' => $region->districts
        ]);
    }
}

resources/views/regions/_form.blade.php
{{ csrf_field() }}

<label for="state_id">Estado</label>
<select name="state_id" id="state_id">
    <option disabled selected>Selecione</option>
    @foreach ($states as $id => $state)
        <option value="{{ $id }}"
                @if ($id == old('state_id', $region->city->state_id ?? ''))
                selected
                @endif
        >
            {{ $state }}
        </option>
    @endforeach
</select>

<label for="city_id">Cidade</label>
<select name="city_id" id="city_id">
    <option disabled selected>Selecione</option>
    @foreach ($cities as $id => $city)
        <option value="{{ $id }}"
                @if ($id == old('city_id', $region->city_id))
                selected
                @endif
        >
            {{ $city }}
        </option>
    @endforeach
</select>

<label for="name">Nome</label>
<input type="text" name="name" id="name" value="{{ old('name', $region->name) }}">

<button class="btn btn-primary" type="submit">Salvar</button>

resources/views/regions/create.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Nova Região</h2>
    <a href="/admin/regions">Ver todas</a>
    @include('errors.list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('regions.store') }}">
            @include('regions._form')
        </form>
    </div>
@stop

resources/views/regions/edit.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Editar Região</h2>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('regions.update', [ $region->id ]) }}">
            {{ method_field('PUT') }}
            @include('regions._form')
        </form>
    </div>
@stop

resources/views/regions/index.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Regiões</h2>
    <a href="/admin/regions/create">Adicionar nova</a>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="GET" action="{{ route('regions.index') }}">
            @include('partials._search')
        </form>
        <table>
            <thead>
            <tr>
                <th>Nome</th>
                <th>Cidade</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($regions as $region)
                <tr>
                    <td>{{ $region->name }}</td>
                    <td>{{ $region->city->name }}/{{ $region->city->state->abbreviation }}</td>
                    <td>
                        <a href="{{ action('RegionsController@show', $region->id) }}" class="btn btn-primary btn-xs">
                            Ver
                        </a>
                        <a href="{{ action('RegionsController@edit', $region->id) }}" class="btn btn-info btn-xs">
                            Editar
                        </a>
                        <form method="POST"
                              class="form--inline"
                              action="{{ action('RegionsController@destroy', [ $region->id ]) }}"
                        >
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger btn-xs">
                                Excluir
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $regions->render() !!}
    </div>
@stop

resources/views/regions/show.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Região: {{ $region->name }}</h2>
    <div class="dash-content">

        <h3>Bairros</h3>
        <table>
            <thead>
            <tr>
                <th>Nome</th>
                <th>Visualizar</th>
            </tr>
            </thead>
            <tbody>
            @foreach($region->districts as $district)
                <tr>
                    <td>{{ $district->name }}</td>
                    <td>
                        <a href="{{ action('DistrictsController@show', $district->id) }}" class="btn btn-primary btn-xs">
                            Ver
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop