routes/admin.php
<?php

Route::get('/', 'AdminController@index')->name('home');
Route::get('reports', 'ReportsController@index')->name('reports');

//User and Authentications related
Route::resource('roles', 'RolesController');
Route::resource('users', 'UsersController');

//Visit related
Route::resource('visits', 'VisitsController');
Route::resource('visit-types', 'VisitTypesController');
Route::resource('activities', 'ActivitiesController');
Route::resource('larvae', 'LarvaeController');
Route::resource('building-statuses', 'BuildingStatusesController');
Route::resource('containers', 'ContainersController');
Route::resource('treatments', 'TreatmentsController');

//Notification related
Route::get('notifications/status', 'ReportsController@notificationsByStatus');
Route::get('notifications/age', 'ReportsController@notificationsByAge');
Route::get('notifications/regions', 'ReportsController@notificationsByRegion');
Route::resource('notifications', 'NotificationsController');
Route::resource('examinations', 'ExaminationsController');

//Location related
//State
Route::get('states/{id}/cities', 'StatesController@cities');
Route::get('states/search', 'StatesController@search');
Route::resource('states', 'StatesController');
//City
Route::get('cities/{id}/regions', 'CitiesController@regions');
Route::get('cities/search', 'CitiesController@search');
Route::resource('cities', 'CitiesController');
//Region
Route::get('regions/{id}/districts', 'RegionsController@districts');
Route::get('regions/search', 'RegionsController@search');
Route::resource('regions', 'RegionsController');
//District
Route::get('districts/{id}/streets', 'DistrictsController@streets');
Route::get('districts/search', 'DistrictsController@search');
Route::resource('districts', 'DistrictsController');
//Streets
Route::get('streets/{id}/buildings', 'StreetsController@getBuildings');
Route::get('streets/search', 'StreetsController@search');
Route::resource('streets', 'StreetsController');
//Buildings
Route::get('buildings/search', 'BuildingsController@search');
Route::resource('buildings', 'BuildingsController');
Route::resource('building-types', 'BuildingTypesController');

//Settings
Route::get('settings', 'SettingsController@index');
Route::post('settings', 'SettingsController@store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
$router->get('/', 'PublicController@index');
$router->get('vigilancia', 'PublicController@vigilancia');
$router->get('dengue', 'PublicController@dengue');
$router->get('contato', [ 'as' => 'contato', 'uses' => 'PublicController@getContato' ]);
$router->post('contato', 'PublicController@postContato');
$router->get('notifications/points', 'NotificationsController@positives');
$router->get('visits/points', 'VisitsController@getPoints');
$router->get('geocoding/{address}', 'ApiController@getGeocoding');

$router->auth();

app/City.php
<?php

namespace AlphaDengue;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'state_id'
    ];

    /**
     * Retrieves the state of this city
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function state()
    {
        return $this->belongsTo(State::class);
    }

    /**
     * Retrieves the regions of this city
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function regions()
    {
        return $this->hasMany(Region::class)->orderBy('name');
    }
}

app/Http/Controllers/CitiesController.php
<?php

namespace AlphaDengue\Http\Controllers;

use AlphaDengue\City;
use \AlphaDengue\State;
use Illuminate\Http\Request;
use AlphaDengue\Http\Requests\CityRequest;

class CitiesController extends Controller
{
    private $city;

    /**
     * CitiesController constructor.
     * @param City $city
     */
    public function __construct(City $city)
    {
        $this->city = $city;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $citiesQuery = $this->city->orderBy('name');

        if ($request->has('q')) {
            $query = $request->query('q');
            $citiesQuery = $citiesQuery->where('name', 'ilike', '%' . $query . '%');
        }

        $cities = $citiesQuery->with('state')->paginate();

        return view('cities.index', compact('cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param State $state The state entity
     *
     * @return \Illuminate\Http\Response
     */
    public function create(State $state)
    {
        $city = new City;
        $states = $state->orderBy('name')->pluck('name', 'id');

        return view('cities.create', compact('city', 'states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CityRequest $request The incoming request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CityRequest $request)
    {
        $this->city->create($request->all());

        $request->session()->flash('message_type', 'success');
        $request->session()->flash('message', 'Município cadastrado com sucesso!');

        return redirect('/admin/cities');
    }

    /**
     * Display the specified resource.
     *
     * @param City $city
     * @param \Illuminate\Http\Request $request The current request
     *
     * @return \Illuminate\Http\Response
     */
    public function show(City $city, Request $request)
    {
        return view('cities.show', compact('city'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city, State $state)
    {
        $states = $state->orderBy('name')->pluck('name', 'id');

        return view('cities.edit', compact('city', 'states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @param CityRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update($id, CityRequest $request)
    {
        $city = City::findOrFail($id);
        $city->update($request->all());

        $request->session()->flash('message_type', 'success');
        $request->session()->flash('message', 'Município atualizado com sucesso!');

        return redirect('/admin/cities');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete_count = City::destroy($id);

        if ($delete_count != 1) {
            session()->flash('message_type', 'danger');
            session()->flash('message', 'Erro ao excluir município!');
        } else {
            session()->flash('message_type', 'success');
            session()->flash('message', 'Município excluido com sucesso!');
        }

        return redirect('/admin/cities');
    }

    /**
     * Get the regions of the city
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function regions($id)
    {
        $city = City::findOrFail($id);

        return response()->json([
            'data' => $city->regions
        ]);
    }

    /**
     * Searches a city by the name criteria
     *
     * @param Request $request
     * @return \Illuminate\View\View
     */
    public function search(Request $request)
    {
        $query = $request->input('q');
        $cities = City::where('name', 'ilike', '%' . $query . '%')->orderBy('name');

        if ($request->ajax()) {
            return $cities->get();
        }

        $cities = $cities->paginate();

        return view('cities.index', compact('cities'));
    }
}

resources/views/cities/_form.blade.php
{{ csrf_field() }}

<label for="state_id">Estado</label>
<select name="state_id" id="state_id">
    <option disabled selected>Selecione</option>
    @foreach ($states as $id => $state)
        <option value="{{ $id }}"
                @if ($id == old('state_id', $city->state_id))
                selected
                @endif
        >
            {{ $state }}
        </option>
    @endforeach
</select>

<label for="name">Nome</label>
<input type="text" name="name" id="name" value="{{ old('name', $city->name) }}">

<button class="btn btn-primary" type="submit">Salvar</button>

resources/views/cities/create.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Novo Município</h2>
    <a href="/admin/cities">Ver todas</a>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('cities.store') }}">
            @include('cities._form')
        </form>
    </div>
@stop

resources/views/cities/edit.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Editar Município</h2>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('cities.update', [ $city->id ]) }}">
            {{ method_field('PUT') }}
            @include('cities._form')
        </form>
    </div>
@stop

resources/views/cities/index.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Municípios</h2>
    <a href="{{ route('cities.create') }}">Adicionar novo</a>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="GET" action="{{ route('cities.index') }}">
            @include('partials._search')
        </form>
        <table>
            <thead>
            <tr>
                <th>Nome</th>
                <th>Estado</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($cities as $city)
                <tr>
                    <td>{{ $city->name }}</td>
                    <td>{{ $city->state->name }}</td>
                    <td>
                        <a href="{{ action('CitiesController@show', $city->id) }}" class="btn btn-primary btn-xs">
                            Ver
                        </a>
                        <a href="{{ action('CitiesController@edit', $city->id) }}" class="btn btn-info btn-xs">
                            Editar
                        </a>
                        <form method="POST"
                              class="form--inline"
                              action="{{ action('CitiesController@destroy', [ $city->id ]) }}"
                        >
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger btn-xs">
                                Excluir
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $cities->appends(request()->query())->render() }}
    </div>
@stop

resources/views/cities/show.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Município: {{ $city->name }}</h2>
    <div class="dash-content">

        <h3>Regiões</h3>
        <table>
            <thead>
            <tr>
                <th>Nome</th>
                <th>Visualizar</th>
            </tr>
            </thead>
            <tbody>
            @foreach($city->regions as $region)
                <tr>
                    <td>{{ $region->name }}</td>
                    <td>
                        <a href="{{ action('RegionsController@show', $region->id) }}" class="btn btn-primary btn-xs">
                            Ver
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <h3>Relatórios</h3>
        <form action="">
            <label for="from-date">Desde:</label>
            <input type="date" id="from-date">

            <label for="to-date">Até:</label>
            <input type="date" id="to-date">

            <button class="btn btn-success">Atualizar</button>
        </form>

        <div class="report-box">
            <h4>Geral</h4>
            <div class="report-graph">
                <canvas id="general-chart" class="chart"></canvas>
            </div>
            <div class="report-table"></div>
        </div>

        <div class="report-box">
            <h4>Por faixa etária</h4>
            <div class="report-graph">
                <canvas id="age-chart" class="chart"></canvas>
            </div>
            <div class="report-table"></div>
        </div>

        <div class="report-box">
            <h4>Por região</h4>
            <div class="report-graph">
                <canvas id="region-chart" class="chart"></canvas>
            </div>
            <div class="report-table"></div>
        </div>
    </div>
@stop