routes/admin.php
<?php

Route::get('/', 'AdminController@index')->name('home');
Route::get('reports', 'ReportsController@index')->name('reports');

//User and Authentications related
Route::resource('roles', 'RolesController');
Route::resource('users', 'UsersController');

//Visit related
Route::resource('visits', 'VisitsController');
Route::resource('visit-types', 'VisitTypesController');
Route::resource('activities', 'ActivitiesController');
Route::resource('larvae', 'LarvaeController');
Route::resource('building-statuses', 'BuildingStatusesController');
Route::resource('containers', 'ContainersController');
Route::resource('treatments', 'TreatmentsController');

//Notification related
Route::get('notifications/status', 'ReportsController@notificationsByStatus');
Route::get('notifications/age', 'ReportsController@notificationsByAge');
Route::get('notifications/regions', 'ReportsController@notificationsByRegion');
Route::resource('notifications', 'NotificationsController');
Route::resource('examinations', 'ExaminationsController');

//Location related
//State
Route::get('states/{id}/cities', 'StatesController@cities');
Route::get('states/search', 'StatesController@search');
Route::resource('states', 'StatesController');
//City
Route::get('cities/{id}/regions', 'CitiesController@regions');
Route::get('cities/search', 'CitiesController@search');
Route::resource('cities', 'CitiesController');
//Region
Route::get('regions/{id}/districts', 'RegionsController@districts');
Route::get('regions/search', 'RegionsController@search');
Route::resource('regions', 'RegionsController');
//District
Route::get('districts/{id}/streets', 'DistrictsController@streets');
Route::get('districts/search', 'DistrictsController@search');
Route::resource('districts', 'DistrictsController');
//Streets
Route::get('streets/{id}/buildings', 'StreetsController@getBuildings');
Route::get('streets/search', 'StreetsController@search');
Route::resource('streets', 'StreetsController');
//Buildings
Route::get('buildings/search', 'BuildingsController@search');
Route::resource('buildings', 'BuildingsController');
Route::resource('building-types', 'BuildingTypesController');

//Settings
Route::get('settings', 'SettingsController@index');
Route::post('settings', 'SettingsController@store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
$router->get('/', 'PublicController@index');
$router->get('vigilancia', 'PublicController@vigilancia');
$router->get('dengue', 'PublicController@dengue');
$router->get('contato', [ 'as' => 'contato', 'uses' => 'PublicController@getContato' ]);
$router->post('contato', 'PublicController@postContato');
$router->get('notifications/points', 'NotificationsController@positives');
$router->get('visits/points', 'VisitsController@getPoints');
$router->get('geocoding/{address}', 'ApiController@getGeocoding');

$router->auth();

app/Http/Controllers/VisitTypesController.php
<?php

namespace AlphaDengue\Http\Controllers;

use AlphaDengue\Http\Requests;
use AlphaDengue\Http\Controllers\Controller;
use AlphaDengue\Http\Requests\VisitTypeRequest;
use AlphaDengue\VisitType;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class VisitTypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $visit_types = VisitType::all();

        return view('visit-types.index', compact('visit_types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('visit-types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param VisitTypeRequest $request
     * @return Response
     */
    public function store(VisitTypeRequest $request)
    {
        $visit_type = VisitType::create($request->all());

        if ($request->ajax()) {
            return $visit_type;
        }

        $request->session()->flash('message_type', 'success');
        $request->session()->flash('message', 'Tipo de visita criado com sucesso!');

        return redirect('admin/visit-types');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        return VisitType::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $visit_type = VisitType::findOrFail($id);
        return view('visit-types.edit', compact('visit_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @param VisitTypeRequest $request
     * @return Response
     */
    public function update($id, VisitTypeRequest $request)
    {
        $visit_type = VisitType::findOrFail($id);
        $visit_type->update($request->all());

        \Session::flash('message_type', 'success');
        \Session::flash('message', 'Tipo de visita atualizada com sucesso!');

        return redirect('/admin/visit-types');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(VisitType $visit_type)
    {
        try {
            $visit_type->delete();

            session()->flash('message_type', 'success');
            session()->flash('message', 'Tipo de visita excluida com sucesso!');
        } catch (QueryException $e) {
            session()->flash('message_type', 'danger');
            session()->flash('message', 'Erro ao excluir tipo de visita!');
        }

        return redirect('/admin/visit-types');
    }
}

resources/views/visit-types/_form.blade.php
{{ csrf_field() }}
<label for="name">Descrição:</label>
<input type="text" name="name" id="name" value="{{ old('name') ?? $visit_type->name ?? '' }}">
<button type="submit" class="btn btn-primary">Salvar</button>

resources/views/visit-types/create.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Novo Tipo de Visita</h2>
    <a href="/admin/visit-types">Ver todos</a>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('visit-types.store') }}">
            @include('visit-types._form')
        </form>
    </div>
@stop

resources/views/visit-types/edit.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Editar Tipo de Visita</h2>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <form method="POST" action="{{ route('visit-types.update', [ $visit_type->id ]) }}">
            {{ method_field('PUT') }}
            @include('visit-types._form')
        </form>
    </div>
@stop

resources/views/visit-types/index.blade.php
@extends('admin')

@section('content')
    <h2 class="dashboard-title">Tipos de Visita</h2>
    <a href="/admin/visit-types/create">Adicionar novo</a>
    @include('errors/list')
    @include('partials._messages')
    <div class="dash-content">
        <table>
            <thead>
            <tr>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($visit_types as $type)
                <tr>
                    <td>{{ $type->name }}</td>
                    <td>
                        <a href="{{ action('VisitTypesController@show', $type->id) }}" class="btn btn-primary btn-xs">
                            Ver
                        </a>
                        <a href="{{ action('VisitTypesController@edit', $type->id) }}" class="btn btn-info btn-xs">
                            Editar
                        </a>
                        <form method="POST"
                              class="form--inline"
                              action="{{ action('VisitTypesController@destroy', [ $type->id ]) }}"
                        >
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger btn-xs">
                                Excluir
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop